
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/association
    username: root
    password: P@sser123
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
